-- 1. Lấy danh sách (MaSanPham, TenSanPham, GiaSanPham, TenHangSanXuat) các sản phẩm của hãng Lamaze
-- 2. Lấy danh sách (MaSanPham, TenSanPham, GiaSanPham, TenHangSanXuat) các sản phẩm của hãng có tên bắt đầu bằng chữ 'L'
-- 3. Lấy danh sách (MaSanPham, TenSanPham, GiaSanPham) các sản phẩm có tên tồn tại chữ "a"
-- 4. Lấy danh sách (MaSanPam, TenSanPham, GiaSanPham) có giá bán lớn hơn 1tr
-- 5. Lấy danh sách (MaSanPam, TenSanPham, GiaSanPham) có giá bán nhỏ hơn hơn 500k
-- 6. Lấy danh sách (MaSanPam, TenSanPham, GiaSanPham) có giá bán nhỏ hơn 1tr và lớn hơn hoặc bằng 500k
-- 7. Lấy danh sách (MaSanPham, TenSanPham, GiaSanPham) Có giá khác 600000
-- 8. Lấy danh sách (MaSanPham, TenSanPham, GiaSanPham) có giá trong khoản 300k đến 600k
-- 9. Lấy danh sách (MaSanPham, TenSanPham, GiaSanPham) có giá thuộc các giá trị sau: 300k, 480k, 600k
-- 10. Lây danh sách (MaSanPham, TenSanPham, GiaSanPham, TenHangSanXuat) không thuộc hãng 'Lamaze' 
-- 11. Lấy danh sách (MaSanPham, TenSanPham, GiaSanPham, TenHangSanXuat) Thuộc hãng 'Lamze' và 'Revell'
-- 12. Lấy danh sách (MaSanPham, TenSanPham, GiaSanPham, TenHangSanXuat) Thuộc hãng 'Lamaze' và có giá bán trên 300k
-- 13. Lấy danh sách (MaSanPham, TenSanPham, GiaSanPham, TenHangSanXuat, TenLoaiSanPham) thuộc hãng 'Lamaze' hoặc thuộc loại 'Đồ chơi điện tử'
-- 14. Lấy danh sách (MaSanPham, TenSanPham, GiaSanPham, TenHangSanXuat, TenLoaiSanPham) thuộc loại 'Thú nhồi bông' hoặc có giá bán trên 400k
-- 15. Lấy danh sách (MaSanPham, TenSanPham, GiaSanPham, TenHangSanXuat, TenLoaiSanPham) không thuộc loại 'Thú nhồi bông' mà có giá bán trên 400k
-- 16. Lấy danh sách (MaSanPham, TenSanPham, GiaSanPham) sắp tăng theo giá bán
-- 17. Lấy danh sách (MaSanPham, TenSanPham, GiaSanPham) sắp giảm theo số lượng tồn
-- 18. Lấy danh sách (MaSanPham, TenSanPham, GiaSanPham) sắp tăng theo giá bán và sắp giảm theo số lượng tồn
-- 19. Lấy danh sách (MaSanPham, TenSanPham, GiaSanPham) sắp giảm theo giá bán và sắp giảm theo số lượng bán
-- 20. Lấy danh sách (TenLoaiSanPham, TongSoLuongTon) tính tổng số lượng tồn của sản phẩm theo từng loại
-- 21. Lấy danh sách (TenHangSanXuat, SoLuongBanTrungBinh) Tính tổng số lượng bán trung bình theo từng hãng
-- 22. Lấy danh sách (MaSanPham, TenSanPham, GiaSanPham) có số lượng bán cao cao nhất
-- 23. Lấy danh sách (MaSanPham, TenSanPham, GiaSanPham) có số lượng bán chậm nhất