USE QL_DeAn

-- PHẦN 05 - PHÉP CHIA
-- 48. Danh sách những nhân viên (HONV, TENLOT, TENNV) làm việc trong
--     mọi đề án của công ty

SELECT N.MANV, N.HONV, N.TENLOT, N.TENNV
FROM NHANVIEN N, PHANCONG P
WHERE N.MANV = P.MA_NVIEN
GROUP BY N.MANV, N.HONV, N.TENLOT, N.TENNV
HAVING COUNT(DISTINCT P.MADA) = (SELECT COUNT(D.MADA) FROM DEAN D)

-- 49. Danh sách những nhân viên (HONV, TENLOT, TENNV) được phân công
--     tất cả đề án do phòng số 4 chủ trì.
SELECT N.MANV, N.HONV, N.TENLOT, N.TENNV
FROM DEAN D, CONGVIEC C, PHANCONG P, NHANVIEN N
WHERE D.MADA = C.MADA AND C.MADA = P.MADA AND C.STT = P.STT
		AND P.MA_NVIEN = N.MANV AND D.PHONG = 4
GROUP BY N.MANV, N.HONV, N.TENLOT, N.TENNV
HAVING COUNT(DISTINCT P.MADA) = (SELECT COUNT(MADA) FROM DEAN WHERE PHONG = 4)

-- 50. Tìm những nhân viên (HONV, TENLOT, TENNV) được phân công (làm chung) tất cả
--     đề án mà nhân viên 'Đinh Bá Tiến' làm việc
SELECT N.MANV, N.HONV, N.TENLOT, N.TENNV
FROM NHANVIEN N, PHANCONG P
WHERE N.MANV = P.MA_NVIEN 
GROUP BY N.MANV, N.HONV, N.TENLOT, N.TENNV
HAVING COUNT(DISTINCT P.MADA) = (SELECT COUNT(DISTINCT PC.MADA)
								 FROM NHANVIEN NV, PHANCONG PC
								 WHERE NV.MANV = PC.MA_NVIEN AND 
								 (NV.HONV + ' ' + NV.TENLOT + ' ' + NV.TENNV) = N'Đinh Bá Tiên')

-- 51. Cho biết những nhân được phân công cho tất cả các công việc trong đề
--     án 'Sản phẩm X'

SELECT N.MANV, N.HONV, N.TENLOT, N.TENNV
FROM NHANVIEN N, PHANCONG P, CONGVIEC C, DEAN D
WHERE N.MANV = P.MA_NVIEN AND P.MADA = C.MADA AND P.STT = C.STT 
		AND C.MADA = D.MADA AND D.TENDA = N'Sản phẩm X'
GROUP BY N.MANV, N.HONV, N.TENLOT, N.TENNV 
HAVING COUNT(P.STT) = (SELECT COUNT(CV.STT)
					   FROM DEAN DA, CONGVIEC CV
					   WHERE DA.MADA = CV.MADA AND DA.TENDA = N'Sản phẩm X'
					   GROUP BY DA.MADA)

-- 52. Cho biết danh sách nhân viên tham gia vào tất cả các đề án ở TP HCM
SELECT N.MANV, N.HONV, N.TENLOT, N.TENNV
FROM NHANVIEN N, PHANCONG P, CONGVIEC C, DEAN D
WHERE N.MANV = P.MA_NVIEN AND P.MADA = C.MADA AND P.STT = C.STT 
		AND C.MADA = D.MADA AND D.DDIEM_DA = N'TP HCM'
GROUP BY N.MANV, N.HONV, N.TENLOT, N.TENNV
HAVING COUNT(DISTINCT P.MADA) = (SELECT COUNT(DA.MADA)
									FROM DEAN DA
									WHERE DA.DDIEM_DA = N'TP HCM')

-- 53. Cho biết phòng ban chủ trì tất cả các đề án ở TP HCM
SELECT P.MAPHG, P.TENPHG
FROM PHONGBAN P, DEAN D
WHERE D.PHONG = P.MAPHG AND D.DDIEM_DA = N'TP HCM'
GROUP BY P.MAPHG, P.TENPHG
HAVING COUNT(D.MADA) = (SELECT COUNT(DA.MADA) 
						FROM DEAN DA 
						WHERE DA.DDIEM_DA = N'TP HCM')